name: Run Selenium Tests

on:
  push:
    branches: ["main"]
  create:
    branches:
      - automation-*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          cache: "maven"
          distribution: 'temurin'
      - uses: browser-actions/setup-chrome@v1
      - run: mvn clean test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results-${{ matrix.marks }}
          path: allure-results-${{ matrix.marks }}

      - name: configure allure using allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history



